# Generated by Django 4.1.3 on 2022-11-21 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_id', models.IntegerField()),
                ('pay_method', models.CharField(max_length=25)),
                ('pay_ammount', models.IntegerField()),
            ],
        ),
    ]
