# Generated by Django 4.1.3 on 2022-11-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Stor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=25)),
                ('book_quntity', models.IntegerField()),
                ('book_price', models.IntegerField()),
                ('book_owner', models.CharField(max_length=25)),
            ],
        ),
    ]
